### ISSUE TITLE
BankManagementSystem using python

### ISSUE THREAD

**Issue by ervikasji** [jeremie1112/All_Programs_and_algorithms#228]
Hi.there i want to contribute in your repo by adding this.pls merge it and mark it  "Hacktoberfest Accepted" .

**Comment by jeremie1112** [comment]
please dont make an issue for a PR.
It is not an issue.

**Comment by ervikasji** [comment]
> please dont make an issue for a PR. It is not an issue.

sure i will keep this in mind next time. 
Thanks for merging PR and Marking it as "Hactoberfest Accepted".
